{{if and .Values.push_notification.public_key .Values.push_notification.private_key }}
apiVersion: v1
kind: Secret
metadata:
    name: vapid-push-notification
type: Opaque
data:
    public_key: {{ .Values.push_notification.public_key | b64enc | quote }}
    private_key: {{ .Values.push_notification.private_key | b64enc | quote }}
---{{end}}
