{{if .Values.rabbitmq_password }}
apiVersion: v1
kind: Secret
metadata:
    name: rabbitmq-secret
type: Opaque
data:
    rabbitmq-password: {{ .Values.rabbitmq_password | b64enc | quote }}
    amqp-uri: {{(print "amqp://imazsak:" .Values.rabbitmq_password "@rabbitmq:5672") | b64enc | quote}}
{{end}}
