{{if and .Values.oauth2.facebook.client_id .Values.oauth2.facebook.client_secret }}
apiVersion: v1
kind: Secret
metadata:
    name: oauth2-facebook
type: Opaque
data:
    client_id: {{ .Values.oauth2.facebook.client_id | b64enc | quote }}
    client_secret: {{ .Values.oauth2.facebook.client_secret | b64enc | quote }}
---{{end}}
{{if and .Values.oauth2.google.client_id .Values.oauth2.google.client_secret }}
apiVersion: v1
kind: Secret
metadata:
    name: oauth2-google
type: Opaque
data:
    client_id: {{ .Values.oauth2.google.client_id | b64enc | quote }}
    client_secret: {{ .Values.oauth2.google.client_secret | b64enc | quote }}
---{{end}}
{{if and .Values.jwt.short_token_secret .Values.jwt.long_token_secret }}
apiVersion: v1
kind: Secret
metadata:
    name: auth-jwt
type: Opaque
data:
    short_token_secret: {{ .Values.jwt.short_token_secret | b64enc | quote }}
    long_token_secret: {{ .Values.jwt.long_token_secret | b64enc | quote }}
---{{end}}
{{if .Values.basic_hook_secret }}
apiVersion: v1
kind: Secret
metadata:
    name: tutelar-imazsak-hook
type: Opaque
data:
    basic_hook_secret: {{ .Values.basic_hook_secret | b64enc | quote }}
---{{end}}
{{if .Values.mongo_database_uri }}
apiVersion: v1
kind: Secret
metadata:
    name: mongo-database-uri
type: Opaque
data:
    uri: {{ .Values.mongo_database_uri | b64enc | quote }}
---{{end}}
