apiVersion: apps/v1
kind: Deployment
metadata:
    name: admin-client
    labels:
        app: admin-client
spec:
    replicas: 1
    selector:
        matchLabels:
            app: admin-client
    template:
        metadata:
            labels:
                app: admin-client
        spec:
            containers:
                - name: admin-client
                  image: "{{ .Values.admin.image }}:{{ .Values.admin.image_version }}"
                  ports:
                      - containerPort: 80
